#! /usr/bin/env php

<?php
require_once 'vendor/autoload.php';

use Commands\{
    ExtractCommand, GreetCommand
};
use Symfony\Component\Console\Application;

$app = new Application('CLI Practice with PHP', '1.0.0');

$app->add(new GreetCommand);
$app->add(new ExtractCommand);

$app->run();